[pytest]
testpaths = tests

python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

addopts = -v -s --alluredir=allure-results
minversion = 3.11

pythonpath = .

norecursedirs =
    .git
    .venv
    venv

markers =
    home: tests start from home page
    login: tests start from login page
    cookies: tests works with cookie files
    jse: tests for JavaScriptExecutor functions